@startuml
skinparam componentStyle uml2
top to bottom direction

title Component Diagram

package "          " {

    component [View] as V
    component [Controller] as C
    component [Service] as S
    component [Repository] as R

    component [DTO] as D
    component [Mapper] as M
    component [Model] as Mod

    () " " as i1
    () " " as i2
    () " " as i3
    () " " as i4
    () " " as i5
    () " " as i6

    V -right[hidden]- D
    C -right[hidden]- D
    S -right[hidden]- M
    R -right[hidden]- Mod

    V -down-( i1
    i1 -down- C

    C -down-( i2
    i2 -down- S

    S -down-( i3
    i3 -down- R

    D -left- i4
    V -right-( i4
    C -right-( i4
    S -right-( i4

    S -right-( i5
    i5 - M

    M -down-( i6
    R -right-( i6
    i6 - Mod
}
@enduml