@startuml
skinparam style strictuml

title Exceptions Class Diagram

class "std::exception" as exception {
    what() : char*
}

package "         " {
    class InvalidDataException {
        InvalidDataException(message: string)
    }

    class NoDataException {
        NoDataException(message: string)
    }

    class DuplicatedDataException {
        DuplicatedDataException(message: string)
    }
}

exception <|-- InvalidDataException
exception <|-- NoDataException
exception <|-- DuplicatedDataException

@enduml