@startuml
skinparam style strictuml
hide empty members
top to bottom direction
title Model Class Diagram

class Gym {
    - name: string
    - location: string
}

class AthleteContainer {
    + add(athlete: Athlete): void
    + searchByEmail(email: string): Athlete*
    + getAll(): list<Athlete*>
    - nextAthleteNumber(): string
}

class InstructorContainer {
    + add(instructor: Instructor): void
    + getAll(): list<Instructor*>
}

class ModalityContainer {
    + add(modality: Modality): void
    + getAll(): list<Modality*>
}

class RoomContainer {
    + add(room: Room): void
}

class ClassSessionContainer {
    + add(session: ClassSession): void
}

class PaymentContainer {
    + add(payment: Payment): void
}

abstract class User {
    - name: string
    - email: string
    - password: string
    + getName(): string&
}

class Administrator {
}

class Instructor {
    - specialty: string
}

class Athlete {
    - technicalLevel: string
}

class Modality {
    - name: string
    - description: string
    - minimumLevel: string
}

class Room {
    - name: string
    - maximumCapacity: int
}

class ClassSession {
    - duration: int
}

class Schedule {
    - date: string
    - startTime: string
    - endTime: string
}

class Payment {
    - date: string
    - amount: double
    - status: string
}

class ClassEnrollment {
    - enrollmentDate: string
    - status: string
}

User <|-- Administrator
User <|-- Instructor
User <|-- Athlete

Gym "1" *-- "1" AthleteContainer
Gym "1" *-- "1" InstructorContainer
Gym "1" *-- "1" ModalityContainer
Gym "1" *-- "1" RoomContainer
Gym "1" *-- "1" ClassSessionContainer

AthleteContainer "1" *-- "*" Athlete
InstructorContainer "1" *-- "*" Instructor
ModalityContainer "1" *-- "*" Modality
RoomContainer "1" *-- "*" Room
ClassSessionContainer "1" *-- "*" ClassSession

ClassSession "1" *-- "1" Schedule
Athlete "1" *-- "*" Payment
Athlete "1" *-- "*" ClassEnrollment
ClassEnrollment "*" -- "1" ClassSession

@enduml