@startuml
skinparam style strictuml

title Package Diagram

package "          " {
    package "views"
    package "controllers"
    package "services"
    package "repo"
    package "containers"
    package "model"
    package "dto"
    package "mappers"
    package "exceptions"

    file "main.cpp" as main
}

main --> controllers
main --> services
main --> repo

views --> dto

controllers --> services
controllers --> dto
controllers --> exceptions
controllers --> views

services --> repo
services --> mappers
services --> dto
services --> exceptions
services --> containers

repo --> model
containers --> model
mappers --> dto
mappers --> model

@enduml