@startuml
title UC2 - Registar Instrutor

actor "Administrativo" as Admin

participant "controller:Controller" as Controller
participant "view:View" as View
participant "instructorView:InstructorView" as InstructorView
participant ":Utils" as Utils
participant "instructorDTO:InstructorInDTO" as InstructorDTO
participant "instructorService:InstructorService" as InstructorService
participant "repo:GymRepositoryMemory" as Repo
participant "model:Gym" as Gym
participant "instructorContainer:InstructorContainer" as InstructorContainer
participant "instructor:Instructor" as Instructor

Admin -> Controller : select UC2

Controller -> View : menuGym()
View --> Controller : option

Controller -> InstructorView : getInstructor()

InstructorView -> InstructorDTO : <<create>>

InstructorView -> Utils : getString()
Utils --> InstructorView : name

InstructorView -> Utils : getString()
Utils --> InstructorView : email

InstructorView -> Utils : getString()
Utils --> InstructorView : password

InstructorView -> Utils : getString()
Utils --> InstructorView : specialty

InstructorView -> InstructorDTO : assign data

InstructorView --> Controller : instructorDTO

Controller -> InstructorService : add(instructorDTO)

InstructorService -> Repo : getModel()
Repo --> InstructorService : model

InstructorService -> Gym : getInstructorContainer()
Gym --> InstructorService : instructorContainer

InstructorService -> InstructorContainer : add(instructorDTO)

InstructorContainer -> InstructorContainer : nextInstructorNumber()

InstructorContainer -> Instructor : <<create>>

InstructorContainer --> InstructorService : instructor

InstructorService --> Controller : success

Controller --> Admin : instructor registered

@enduml