@startuml
title Functional Requirements (III)

actor User
participant System

User -> System : 1. Enters athlete data
User -> System : 2. Saves athlete data

System -> System : 2.1 Validates athlete data

alt [Athlete data: true]

System -> System : 2.2 Stores athlete data
System --> User : return success

else [Athlete data: false]

System --> User : return failure

end

@enduml