@startuml
title Functional Requirements (VII)

caption SSD: UC10 - Book ClassSession

actor User
participant System

User -> System : 1. Request the list of athletes
System --> User : 1.1 List of athletes

User -> System : 2. Selects an athlete
System --> User : 2.1 Athlete

User -> System : 3. Request the list of class sessions
System --> User : 3.1 List of class sessions

User -> System : 4. Selects a class session
System --> User : 4.1 Class session

User -> System : 5. Register booking (athlete, class session)

System -> System : 5.1 Validates payment status
System -> System : 5.2 Validates technical level
System -> System : 5.3 Validates class capacity

alt [Booking data: true]

System -> System : 5.4 Stores booking
System --> User : return success

else [Booking data: false]

System --> User : return failure

end

@enduml