@startuml
title Functional Requirements (V)

caption SSD: UC6 - Enroll Athlete in Modality

actor User
participant System

User -> System : 1. Request the list of athletes
System --> User : 1.1 List of athletes

User -> System : 2. Selects an athlete
System --> User : 2.1 Athlete

User -> System : 3. Request the list of modalities
System --> User : 3.1 List of modalities

User -> System : 4. Selects a modality
System --> User : 4.1 Modality

User -> System : 5. Register enrollment (athlete, modality)

System -> System : 5.1 Validates enrollment data

alt [Enrollment data: true]

System --> User : return success

else [Enrollment data: false]

System --> User : return failure

end

@enduml